version: "3.5"

networks:                
    tier:
        internal: true
        
    internet:

services:
    job-vacancies:
        build: .
        networks:
            internet:
            tier:
                aliases:
                    - job-vacancies
        ports:
            - 4050:4050
            - 8080:8080
        volumes:
            - ./webserver:/app
            
    mongodb:
        image: bitnami/mongodb:4.0
        networks:
            tier:
                aliases:
                    - mongodb
        environment:
          - MONGODB_USERNAME=vacancies
          - MONGODB_PASSWORD=nCvm1l9uNg9ZzXowy
          - MONGODB_DATABASE=vacancies
        volumes:
         - ./data:/bitnami